"""Conformance check for the shipping art in assets/.

Run:  python3 tools/check_palette.py [--stats]

Three hard rules, from the art brief:
  1. exact pixel size            — the sizes table in tools/h11_palette.json
  2. alpha is strictly 0 or 255  — Sprite3D alpha_cut = 1 turns any partial
                                   alpha into a jagged stump
  3. every opaque pixel is an entry of Doom's PLAYPAL — tools/playpal-base.lmp

Rule 3 is checked in two tiers, because they fail for different reasons:
  FAIL  the colour is not in PLAYPAL at all — a hand-picked literal, the exact
        defect the "colours come from a ramp" rule exists to prevent
  warn  the colour is a real PLAYPAL entry but is outside the 165-colour working
        set in h11_palette.json (those ramps are the colours used by two or more
        Freedoom reference files, so they are a subset, not the whole palette)

--stats also prints unique colour count and the luminance spread, to compare
against the Freedoom benchmark the art was measured on (median 21%, p90 39%).
Luminance is Rec.709 on the 8-bit values, opaque pixels only.

Pure stdlib on purpose: Pillow is not installed on the development machine, and
the art is regenerated by tools/gen_assets.mjs (Node), not by Python.
Exits 0 if every file passes, 1 otherwise.
"""
import json
import os
import struct
import sys
import zlib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS = os.path.join(ROOT, "assets")
PALETTE = os.path.join(ROOT, "tools", "h11_palette.json")


def read_rgba(path):
    """Decode an 8-bit RGBA PNG into (width, height, bytes). Raises on anything else."""
    data = open(path, "rb").read()
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise ValueError("not a PNG")
    pos, idat, w, h = 8, [], 0, 0
    while pos < len(data):
        length, kind = struct.unpack(">I4s", data[pos:pos + 8])
        body = data[pos + 8:pos + 8 + length]
        if kind == b"IHDR":
            w, h, depth, colour, _, _, interlace = struct.unpack(">IIBBBBB", body)
            if (depth, colour) != (8, 6):
                raise ValueError("expected 8-bit RGBA, got depth=%d colour_type=%d" % (depth, colour))
            if interlace:
                raise ValueError("interlaced PNGs are not supported")
        elif kind == b"IDAT":
            idat.append(body)
        elif kind == b"IEND":
            break
        pos += 12 + length  # length + type + data + crc

    raw = zlib.decompress(b"".join(idat))
    stride = w * 4
    out = bytearray(stride * h)
    prev = bytearray(stride)
    pos = 0
    for y in range(h):
        flt = raw[pos]
        line = bytearray(raw[pos + 1:pos + 1 + stride])
        pos += 1 + stride
        if flt == 1:  # Sub
            for i in range(4, stride):
                line[i] = (line[i] + line[i - 4]) & 0xFF
        elif flt == 2:  # Up
            for i in range(stride):
                line[i] = (line[i] + prev[i]) & 0xFF
        elif flt == 3:  # Average
            for i in range(stride):
                left = line[i - 4] if i >= 4 else 0
                line[i] = (line[i] + ((left + prev[i]) >> 1)) & 0xFF
        elif flt == 4:  # Paeth
            for i in range(stride):
                a = line[i - 4] if i >= 4 else 0
                b = prev[i]
                c = prev[i - 4] if i >= 4 else 0
                p = a + b - c
                pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
                pred = a if (pa <= pb and pa <= pc) else (b if pb <= pc else c)
                line[i] = (line[i] + pred) & 0xFF
        elif flt != 0:
            raise ValueError("unknown PNG filter %d on row %d" % (flt, y))
        out[y * stride:(y + 1) * stride] = line
        prev = line
    return w, h, bytes(out)


def percentile(values, q):
    if not values:
        return 0.0
    i = min(len(values) - 1, int(len(values) * q))
    return values[i]


def load_playpal(path):
    """The 256 RGB triples of Doom's base palette (the first of PLAYPAL's 14)."""
    d = open(path, "rb").read()
    return {(d[i * 3], d[i * 3 + 1], d[i * 3 + 2]) for i in range(256)}


def check(name, size, allowed, want_stats):
    path = os.path.join(ASSETS, name + ".png")
    if not os.path.exists(path):
        return ["missing file"], ""
    try:
        w, h, px = read_rgba(path)
    except ValueError as e:
        return [str(e)], ""

    problems = []
    if [w, h] != list(size):
        problems.append("size %dx%d, expected %dx%d" % (w, h, size[0], size[1]))

    ramps, playpal = allowed
    partial = 0
    offpalette = {}
    offramp = set()
    colours = set()
    lums = []
    for i in range(0, len(px), 4):
        a = px[i + 3]
        if a == 0:
            continue
        if a != 255:
            partial += 1
            continue
        rgb = (px[i], px[i + 1], px[i + 2])
        colours.add(rgb)
        if rgb not in ramps:
            key = "#%02X%02X%02X" % rgb
            if rgb in playpal:
                offramp.add(key)
            else:
                offpalette[key] = offpalette.get(key, 0) + 1
        if want_stats:
            lums.append(0.2126 * rgb[0] + 0.7152 * rgb[1] + 0.0722 * rgb[2])

    if partial:
        problems.append("%d semi-transparent pixels (alpha must be 0 or 255)" % partial)
    if offpalette:
        worst = sorted(offpalette.items(), key=lambda kv: -kv[1])[:3]
        problems.append("not in PLAYPAL: %s" % ", ".join("%s x%d" % (c, n) for c, n in worst))

    stats = ""
    if offramp:
        stats = "warn: PLAYPAL but off-ramp %s  " % " ".join(sorted(offramp))
    if want_stats:
        lums.sort()
        stats += "%3d colours  median %2.0f%%  p90 %2.0f%%" % (
            len(colours), percentile(lums, 0.5) / 2.55, percentile(lums, 0.9) / 2.55)
    return problems, stats


def main():
    want_stats = "--stats" in sys.argv[1:]
    spec = json.load(open(PALETTE))
    ramps = set()
    for entry in spec["all_colours"]:
        e = entry.lstrip("#")
        ramps.add((int(e[0:2], 16), int(e[2:4], 16), int(e[4:6], 16)))
    playpal = load_playpal(os.path.join(ROOT, "tools", "playpal-base.lmp"))

    failed = 0
    for name in sorted(spec["sizes"]):
        problems, stats = check(name, spec["sizes"][name], (ramps, playpal), want_stats)
        if problems:
            failed += 1
            print("FAIL %-14s %s" % (name, "; ".join(problems)))
        else:
            print("ok   %-14s %s" % (name, stats))

    total = len(spec["sizes"])
    print("\n%d/%d files conform to the palette, alpha and size rules" % (total - failed, total))
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
